### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jpliratavares** [AnonymousSportStacker/discord.js-v12-bot-tutorial-episodes-10-and-on#1]
(node:5196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
    at Object.run (C:\Users\Harmonia\Desktop\EZbot\comandos\giveaway.js:26:33)
    at Client.<anonymous> (C:\Users\Harmonia\Desktop\EZbot\index.js:21:21)
    at Client.emit (events.js:310:20)
    at MessageCreateAction.handle (C:\Users\Harmonia\Desktop\EZbot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Harmonia\Desktop\EZbot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Harmonia\Desktop\EZbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Harmonia\Desktop\EZbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\Harmonia\Desktop\EZbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Harmonia\Desktop\EZbot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:310:20)
(node:5196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by splatboy20081** [comment]
That is because you didn't set up the package.json right.

**Comment by OnHamzaYT** [comment]
I have very well configured my package.json and I have the same error

**Comment by RedolentHalo** [comment]
i am also having same problem

**Comment by RedolentHalo** [comment]
> That is because you didn't set up the package.json right.

no
